import { z } from "zod";
import { animationSettingsSchema } from "./animation-settings";

const tokens = z.record(
  z.string().regex(/^--[a-z0-9-]+$/),
  z.string().min(1).max(1024),
);
export const appearancePresetSchema = z
  .object({
    version: z.literal("1"),
    nameEn: z.string().min(1).max(120),
    nameHe: z.string().min(1).max(120),
    capturedOn: z.string().date(),
    sourceRevision: z.string().datetime({ offset: true }).nullable(),
    animationSettings: animationSettingsSchema,
    themeTokens: z
      .object({ dark: tokens, medium: tokens, light: tokens })
      .strict(),
    baseStyles: z.array(z.string().min(1).max(160)).min(1).max(12),
  })
  .strict()
  .refine(
    (value) => value.animationSettings.appearanceVersion === "1",
    "Version1 backup must restore Version1",
  );

export type AppearancePreset = z.infer<typeof appearancePresetSchema>;

// Effective public tokens were recorded from the deployed baseline before the
// Version2 overlay. Measured header geometry is deliberately excluded.
export const VERSION_ONE_APPEARANCE: AppearancePreset = {
  version: "1",
  nameEn: "Version1 — original appearance and animation backup",
  nameHe: "גרסה1 — גיבוי העיצוב וההנפשות המקוריים",
  capturedOn: "2026-10-02",
  sourceRevision: null,
  animationSettings: {
    appearanceVersion: "1",
    enabled: true,
    features: {
      themeReveal: true,
      themeIcon: true,
      navigationProgress: true,
      pageReveal: true,
      contentReveal: true,
      skeletonShimmer: true,
      imageReveal: true,
      dialogs: true,
      menus: true,
      buttonFeedback: true,
      microInteractions: true,
      ambientMotion: true,
      textRails: true,
    },
    durations: {
      theme: 420,
      icon: 180,
      navigation: 180,
      page: 220,
      content: 160,
      skeleton: 1400,
      image: 160,
      dialog: 200,
      menu: 150,
      button: 160,
      micro: 150,
    },
    themeStyle: "radial",
    pageStyle: "lift",
    easing: "standard",
  },
  themeTokens: {
    dark: {
      "--background": "#000",
      "--surface": "#080808",
      "--surface-muted": "#101010",
      "--surface-hover": "#1a1a1a",
      "--foreground": "#fff",
      "--muted-foreground": "#c8c8c8",
      "--border-subtle": "#595959",
      "--border-control": "#969696",
      "--primary": "gold",
      "--primary-hover": "#ffe766",
      "--primary-foreground": "#111214",
      "--accent-text": "#ffe44d",
      "--secondary-accent": "#00ffe0",
      "--success-text": "#5cff95",
      "--error-text": "#ff767f",
      "--badge-admin": "#d998ff",
      "--badge-worker": "#69c7ff",
      "--badge-customer": "#5cff95",
      "--badge-suspended": "#ffdf4d",
      "--hero-glow": "#ffd7001a",
      "--header-surface": "#000",
      "--header-surface-strong": "#000",
      "--radius-xs": ".375rem",
      "--radius-sm": ".625rem",
      "--radius-md": ".875rem",
      "--radius-lg": ".75rem",
      "--radius-xl": "1rem",
      "--radius-2xl": "1.5rem",
      "--radius-full": "9999px",
      "--shadow-soft": "0 8px 24px #0009",
      "--shadow-lift": "0 18px 38px #000000bf",
      "--shadow-glow":
        "0 3px 12px #ffd700b3, 0 0 12px #ffd70033, 0 0 24px #ffd70014",
      "--focus-ring": "#00ffe0",
      "--gold-highlight": "#fff3b0",
      "--turquoise-highlight": "#a6fff4",
      "--turquoise-glow": "0 0 10px #00ffe033, 0 0 22px #00ffe014",
    },
    medium: {
      "--background": "#090b0d",
      "--surface": "#121518",
      "--surface-muted": "#1b1f23",
      "--surface-hover": "#23282c",
      "--foreground": "#f5f6f7",
      "--muted-foreground": "#aeb5bc",
      "--border-subtle": "#2c3238",
      "--border-control": "#7e8a95",
      "--primary": "#ffca28",
      "--primary-hover": "#ffda66",
      "--primary-foreground": "#111214",
      "--accent-text": "#ffce42",
      "--secondary-accent": "#69e1d3",
      "--success-text": "#7fe5a2",
      "--error-text": "#ff9a9a",
      "--badge-admin": "#c084fc",
      "--badge-worker": "#60a5fa",
      "--badge-customer": "#4ade80",
      "--badge-suspended": "#fbbf24",
      "--hero-glow": "#f2c21d38",
      "--header-surface": "#0b0e10f0",
      "--header-surface-strong": "#0c1013eb",
      "--radius-xs": ".375rem",
      "--radius-sm": ".625rem",
      "--radius-md": ".875rem",
      "--radius-lg": ".75rem",
      "--radius-xl": "1rem",
      "--radius-2xl": "1.5rem",
      "--radius-full": "9999px",
      "--shadow-soft": "0 8px 24px #0000001f",
      "--shadow-lift": "0 18px 38px #0003",
      "--shadow-glow": "0 3px 12px #ffca2817",
      "--focus-ring": "#ffca28",
      "--gold-highlight": "#fff3b0",
      "--turquoise-highlight": "#a6fff4",
      "--turquoise-glow": "0 0 10px #00ffe033, 0 0 22px #00ffe014",
    },
    light: {
      "--background": "#f7f8fa",
      "--surface": "#fff",
      "--surface-muted": "#edf2ef",
      "--surface-hover": "#e1e7e4",
      "--foreground": "#151b22",
      "--muted-foreground": "#3a4652",
      "--border-subtle": "#c4ccd5",
      "--border-control": "#748391",
      "--primary": "#ffca28",
      "--primary-hover": "#f1bd22",
      "--primary-foreground": "#111214",
      "--accent-text": "#765300",
      "--secondary-accent": "#0d6d60",
      "--success-text": "#0d6f3d",
      "--error-text": "#b12323",
      "--badge-admin": "#7e22ce",
      "--badge-worker": "#1d4ed8",
      "--badge-customer": "#15803d",
      "--badge-suspended": "#92400e",
      "--hero-glow": "#f2c21d24",
      "--header-surface": "#fffffff0",
      "--header-surface-strong": "#fffffff5",
      "--radius-xs": ".375rem",
      "--radius-sm": ".625rem",
      "--radius-md": ".875rem",
      "--radius-lg": ".75rem",
      "--radius-xl": "1rem",
      "--radius-2xl": "1.5rem",
      "--radius-full": "9999px",
      "--shadow-soft": "0 6px 20px #141c230a",
      "--shadow-lift": "0 14px 36px #141c2314",
      "--shadow-glow": "0 3px 10px #835e0012",
      "--focus-ring": "#f2c21d",
      "--gold-highlight": "#fff3b0",
      "--turquoise-highlight": "#a6fff4",
      "--turquoise-glow": "0 0 10px #00ffe033, 0 0 22px #00ffe014",
    },
  },
  baseStyles: [
    "src/app/globals.css",
    "src/styles/premium.css",
    "src/styles/experience.css",
    "src/styles/storefront.css",
    "src/styles/customer-refinement.css",
  ],
};
Object.freeze(VERSION_ONE_APPEARANCE.animationSettings.features);
Object.freeze(VERSION_ONE_APPEARANCE.animationSettings.durations);
Object.freeze(VERSION_ONE_APPEARANCE.animationSettings);
for (const theme of Object.values(VERSION_ONE_APPEARANCE.themeTokens))
  Object.freeze(theme);
Object.freeze(VERSION_ONE_APPEARANCE.themeTokens);
Object.freeze(VERSION_ONE_APPEARANCE.baseStyles);
Object.freeze(VERSION_ONE_APPEARANCE);
