export const cartCopy = {
  en: {
    cartTitle: "Your cart",
    cartIntro: "Review your selected products before continuing.",
    emptyTitle: "Your cart is empty",
    emptyText: "Explore the collection and add products to begin.",
    browse: "Browse products",
    quantity: "Quantity",
    remove: "Remove",
    subtotal: "Estimated subtotal",
    estimateNote:
      "Final availability, delivery cost and pricing are confirmed before payment.",
    checkout: "Continue to checkout",
    checkoutTitle: "Checkout request",
    checkoutIntro:
      "Send an enquiry. Stock is checked when you submit, but is not reserved; MIRO will confirm availability, shipping and the final total.",
    contact: "Contact details",
    shipping: "Shipping details",
    summary: "Order summary",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    address: "Street address",
    city: "City",
    postalCode: "Postal code",
    notes: "Delivery notes (optional)",
    submit: "Send checkout request",
    submitting: "Sending request…",
    successTitle: "Your request was received",
    successText:
      "We will contact you to confirm availability, delivery and the final amount. No payment has been taken.",
    backToStore: "Continue shopping",
    requiredError: "Please complete all required fields.",
    emailError: "Enter a valid email address.",
    unavailable: "Checkout is unavailable right now. Please try again later.",
    noPayment:
      "No online payment is collected and no stock is reserved on this page.",
  },
  he: {
    cartTitle: "סל הקניות שלכם",
    cartIntro: "בדקו את המוצרים שבחרתם לפני שממשיכים.",
    emptyTitle: "סל הקניות ריק",
    emptyText: "אפשר לבחור מוצרים מהחנות ולהוסיף אותם לסל.",
    browse: "לכל המוצרים",
    quantity: "כמות",
    remove: "הסרה",
    subtotal: "סכום ביניים משוער",
    estimateNote: "זמינות, עלות משלוח ומחיר סופי יאושרו לפני תשלום.",
    checkout: "המשך לפרטי המשלוח",
    checkoutTitle: "בקשת הזמנה ומשלוח",
    checkoutIntro:
      "שלחו בקשה. המלאי נבדק בשליחה אך אינו נשמר; MIRO תאשר זמינות, משלוח וסכום סופי.",
    contact: "פרטי קשר",
    shipping: "פרטי משלוח",
    summary: "סיכום ההזמנה",
    name: "שם מלא",
    email: "דוא״ל",
    phone: "טלפון",
    address: "כתובת רחוב",
    city: "עיר",
    postalCode: "מיקוד",
    notes: "הערות למשלוח (לא חובה)",
    submit: "שליחת בקשת ההזמנה",
    submitting: "שולחים את הבקשה…",
    successTitle: "הבקשה התקבלה",
    successText:
      "ניצור איתכם קשר לאישור זמינות, משלוח והסכום הסופי. לא בוצע חיוב.",
    backToStore: "המשך קניות",
    requiredError: "יש למלא את כל שדות החובה.",
    emailError: "יש להזין כתובת דוא״ל תקינה.",
    unavailable: "לא ניתן להשלים את הבקשה כרגע. נסו שוב מאוחר יותר.",
    noPayment: "לא נגבה תשלום מקוון והמלאי אינו נשמר בעמוד זה.",
  },
} as const;
