type LocaleCode = "he" | "en";
type CopyMap = Record<string, Record<LocaleCode, string>>;

export const salesCopy = {
  pageTitle: { he: "מכירות", en: "Sales" },
  pageSubtitle: {
    he: "רישום מכירה חדשה וצפייה בהיסטוריית המכירות",
    en: "Record a new sale and review the sales history",
  },

  recordSectionTitle: { he: "רישום מכירה", en: "Record sale" },
  recordSectionDescription: {
    he: "בחר לקוח ופריטים, סקור את הסיכום ורשום את המכירה",
    en: "Pick a customer and items, review the totals and record the sale",
  },
  customerSectionTitle: { he: "פרטי לקוח", en: "Customer" },
  accountSearchLabel: {
    he: "חשבון לקוח (חיפוש)",
    en: "Customer account (search)",
  },
  accountSearchPlaceholder: {
    he: "חיפוש לפי שם, אימייל או טלפון…",
    en: "Search by name, email or phone…",
  },
  accountNoResults: { he: "לא נמצאו לקוחות", en: "No customers found" },
  accountLoading: { he: "מחפש לקוחות…", en: "Searching customers…" },
  accountClear: { he: "ניקוי חשבון מקושר", en: "Clear linked account" },
  accountLinkedNote: {
    he: "המכירה תשויך לחשבון זה",
    en: "The sale will be linked to this account",
  },
  guestNote: {
    he: "ללא חשבון — המכירה תירשם כאורח",
    en: "No account — the sale will be recorded as a guest",
  },
  fieldName: { he: "שם מלא", en: "Full name" },
  fieldEmail: { he: "אימייל", en: "Email" },
  fieldPhone: { he: "טלפון", en: "Phone" },
  nameEmailRequired: {
    he: "שם ואימייל נדרשים",
    en: "Name and email are required",
  },
  emailInvalid: { he: "כתובת אימייל לא תקינה", en: "Invalid email address" },

  itemsSectionTitle: { he: "פריטי הזמנה", en: "Order items" },
  productSearchLabel: { he: "מוצר", en: "Product" },
  productSearchPlaceholder: {
    he: "חיפוש לפי שם, SKU או ברקוד…",
    en: "Search by name, SKU or barcode…",
  },
  productNoResults: {
    he: "לא נמצאו מוצרים פעילים",
    en: "No active products found",
  },
  productLoading: { he: "מחפש מוצרים…", en: "Searching products…" },
  productClear: { he: "ניקוי מוצר", en: "Clear product" },
  qty: { he: "כמות", en: "Qty" },
  unitPrice: { he: "מחיר יחידה (ILS)", en: "Unit price (ILS)" },
  discountPerUnit: { he: "הנחה ליחידה (ILS)", en: "Discount per unit (ILS)" },
  removeItem: { he: "הסרת פריט", en: "Remove item" },
  addItem: { he: "הוספת פריט", en: "Add item" },
  stockAvailable: { he: "מלאי זמין", en: "Available stock" },
  stockUntracked: { he: "מלאי לא בניטור", en: "Stock not tracked" },
  variantRequired: { he: "בחר מוצר וגרסה", en: "Choose a product variant" },
  qtyPositive: {
    he: "הכמות חייבת להיות גדולה מ-0",
    en: "Quantity must be greater than 0",
  },
  discountExceedsPrice: {
    he: "ההנחה ליחידה לא יכולה לעלות על מחיר היחידה",
    en: "Discount per unit cannot exceed the unit price",
  },
  itemRequired: {
    he: "הוסף לפחות פריט אחד תקין",
    en: "Add at least one valid item",
  },

  liveGross: { he: "סכום לפני הנחה", en: "Gross before discount" },
  liveDiscounts: { he: "סה״כ הנחות", en: "Total discounts" },
  liveItems: { he: "פריטים", en: "Items" },
  liveTotal: { he: "סה״כ לתשלום", en: "Total due" },

  reviewButton: { he: "סקירת המכירה", en: "Review sale" },
  reviewTitle: {
    he: "סקירת מכירה לפני רישום",
    en: "Review sale before recording",
  },
  reviewDescription: {
    he: "בדוק את הפרטים והסיכומים — הרישום ביצוע אחד במסד הנתונים.",
    en: "Check the details and totals — recording is a single database transaction.",
  },
  reviewCustomerTitle: { he: "לקוח", en: "Customer" },
  reviewAccountGuest: { he: "אורח", en: "Guest" },
  reviewAccountLinked: { he: "חשבון מקושר", en: "Linked account" },
  reviewItemsTitle: { he: "פריטים", en: "Items" },
  colProduct: { he: "מוצר", en: "Product" },
  colSku: { he: "SKU", en: "SKU" },
  colQty: { he: "כמות", en: "Qty" },
  colUnitPrice: { he: "מחיר יחידה", en: "Unit price" },
  colDiscountUnit: { he: "הנחה/יחידה", en: "Discount/unit" },
  colLineDiscount: { he: "הנחה בשורה", en: "Line discount" },
  colGross: { he: "ברוטו", en: "Gross" },
  colVat: { he: 'מע"מ', en: "VAT" },
  colNet: { he: "נטו", en: "Net" },
  reviewSubtotalNet: { he: "סכום ביניים (נטו)", en: "Subtotal (net)" },
  reviewDiscount: { he: "הנחות", en: "Discounts" },
  reviewVat: { he: 'מע"מ', en: "VAT" },
  reviewTotal: { he: "סה״כ לתשלום", en: "Total" },
  cancelLabel: { he: "ביטול", en: "Cancel" },
  confirmRecord: { he: "רישום מכירה", en: "Record sale" },
  recording: { he: "רושם מכירה…", en: "Recording sale…" },
  recordFailed: { he: "רישום המכירה נכשל", en: "Failed to record sale" },
  insufficientStock: {
    he: "מלאי לא מספיק לאחד הפריטים",
    en: "Insufficient stock for one or more items",
  },
  invalidProduct: {
    he: "מוצר או גרסה לא תקינים",
    en: "Invalid product or variant",
  },
  connectionError: { he: "שגיאת חיבור", en: "Connection error" },
  saleRecorded: { he: "המכירה נרשמה", en: "Sale recorded" },
  orderNumberLabel: { he: "מספר הזמנה", en: "Order" },
  noticeDismiss: { he: "סגירת ההתראה", en: "Dismiss notice" },
  vatRateNotePrefix: {
    he: 'מע"מ לפי שיעור נוכחי',
    en: "VAT at the current rate",
  },
  vatRateUnavailable: {
    he: 'שיעור מע"מ לא זמין כעת — סכום מע"מ יסוכם בשרת',
    en: "VAT rate is unavailable — VAT totals are computed by the server",
  },
  vatEstimateNote: {
    he: 'מע"מ משוער — הערך הסופי נקבע במסד הנתונים',
    en: "VAT is an estimate — the final value is set by the database",
  },
} satisfies CopyMap;

export const salesHistoryCopy = {
  sectionTitle: { he: "היסטוריית מכירות", en: "Sales history" },
  sectionDescription: {
    he: "הזמנות שנרשמו במערכת הניהול",
    en: "Orders recorded from the management console",
  },
  tableCaption: { he: "היסטוריית מכירות", en: "Sales history table" },
  colOrder: { he: "הזמנה", en: "Order" },
  colDate: { he: "תאריך", en: "Date" },
  colCustomer: { he: "לקוח", en: "Customer" },
  colRecordedBy: { he: "נרשם על ידי", en: "Recorded by" },
  colItems: { he: "פריטים", en: "Items" },
  colVat: { he: 'מע"מ', en: "VAT" },
  colTotal: { he: "סה״כ", en: "Total" },
  colToggle: { he: "פירוט", en: "Details" },
  expandOrder: { he: "הצגת פרטי הזמנה", en: "Show order details" },
  collapseOrder: { he: "הסתרת פרטי הזמנה", en: "Hide order details" },
  itemProduct: { he: "מוצר", en: "Product" },
  itemSku: { he: "SKU", en: "SKU" },
  itemQty: { he: "כמות", en: "Qty" },
  itemUnitPrice: { he: "מחיר יחידה", en: "Unit price" },
  itemDiscount: { he: "הנחה", en: "Discount" },
  itemVat: { he: 'מע"מ', en: "VAT" },
  itemNet: { he: "נטו", en: "Net" },
  itemTotal: { he: "סה״כ שורה", en: "Line total" },
  guestSuffix: { he: "אורח", en: "guest" },
  emptyTitle: { he: "אין מכירות להצגה", en: "No sales to show" },
  emptyDescription: {
    he: "נסה לשנות את טווח התאריכים.",
    en: "Try changing the date range.",
  },
  errorTitle: {
    he: "טעינת היסטוריית המכירות נכשלה",
    en: "Failed to load sales history",
  },
  retry: { he: "נסה שוב", en: "Try again" },
  clearDates: { he: "כל הזמנים", en: "All time" },
  ordersCount: { he: "הזמנות", en: "orders" },
  prevPage: { he: "הקודם", en: "Previous" },
  nextPage: { he: "הבא", en: "Next" },
  pageOf: { he: "מתוך", en: "of" },
} satisfies CopyMap;
